export const MEAL_TYPES = ["breakfast", "lunch", "dinner"];
// NOTE: Extend statuses to capture love/skip signals for ML ranking.
export const FEEDBACK_STATUSES = new Set(["Accepted", "Rejected", "Loved", "Skipped"]);
export const ML_URL = process.env.ML_SERVICE_URL || "http://127.0.0.1:5001/api/recommendation";
// NOTE: Prime endpoint warms ML caches on login without blocking recommendations.
export const ML_PRIME_URL = process.env.ML_SERVICE_PRIME_URL || "http://127.0.0.1:5001/api/prime";

export const DEFAULT_MEAL_ALLOCATIONS = {
  // NOTE: Default ratios align with combo targets (20/30/50).
  breakfast: 0.20,
  lunch: 0.30,
  dinner: 0.50,
};

export const DEFAULT_DAILY_CALORIES = 2000;

export const SAFETY_LIST_BY_MEAL = {
  breakfast: [
    {
      id: "safety-breakfast-1",
      title: "Greek Yogurt + Berries + Almonds",
      explanation: "Safety fallback: balanced breakfast when live recommendations are unavailable.",
      items: [
        {
          id: "safety-yogurt",
          title: "Greek Yogurt",
          grams: 170,
          calories: 100,
          protein: 17,
          carbs: 6,
          fats: 0,
          image: null,
          type: "food",
          per100: { calories: 59, protein: 10, carbs: 3.6, fats: 0.4 },
        },
        {
          id: "safety-berries",
          title: "Mixed Berries",
          grams: 100,
          calories: 57,
          protein: 1,
          carbs: 14,
          fats: 0,
          image: null,
          type: "food",
          per100: { calories: 57, protein: 0.7, carbs: 14.5, fats: 0.3 },
        },
        {
          id: "safety-almonds",
          title: "Almonds",
          grams: 20,
          calories: 116,
          protein: 4.2,
          carbs: 4.3,
          fats: 10,
          image: null,
          type: "food",
          per100: { calories: 579, protein: 21.2, carbs: 21.6, fats: 49.9 },
        },
      ],
      ml_tag: "Safety",
    },
    {
      id: "safety-breakfast-2",
      title: "Oatmeal + Banana + Milk",
      explanation: "Safety fallback: balanced breakfast with complex carbs and protein.",
      items: [
        {
          id: "safety-oats",
          title: "Oatmeal",
          grams: 70,
          calories: 266,
          protein: 9,
          carbs: 45,
          fats: 5,
          image: null,
          type: "food",
          per100: { calories: 380, protein: 13, carbs: 64, fats: 7 },
        },
        {
          id: "safety-banana",
          title: "Banana",
          grams: 100,
          calories: 89,
          protein: 1,
          carbs: 23,
          fats: 0.3,
          image: null,
          type: "food",
          per100: { calories: 89, protein: 1.1, carbs: 22.8, fats: 0.3 },
        },
        {
          id: "safety-milk",
          title: "Low Fat Milk",
          grams: 200,
          calories: 84,
          protein: 6.8,
          carbs: 10,
          fats: 2,
          image: null,
          type: "food",
          per100: { calories: 42, protein: 3.4, carbs: 5, fats: 1 },
        },
      ],
      ml_tag: "Safety",
    },
  ],
  lunch: [
    {
      id: "safety-lunch-1",
      title: "Grilled Chicken + Brown Rice + Broccoli",
      explanation: "Safety fallback: balanced lunch with lean protein and fiber.",
      items: [
        {
          id: "safety-chicken",
          title: "Grilled Chicken Breast",
          grams: 180,
          calories: 297,
          protein: 56,
          carbs: 0,
          fats: 6,
          image: null,
          type: "food",
          per100: { calories: 165, protein: 31, carbs: 0, fats: 3.6 },
        },
        {
          id: "safety-rice",
          title: "Brown Rice",
          grams: 170,
          calories: 188,
          protein: 4,
          carbs: 39,
          fats: 1.5,
          image: null,
          type: "food",
          per100: { calories: 111, protein: 2.6, carbs: 23, fats: 0.9 },
        },
        {
          id: "safety-broccoli",
          title: "Steamed Broccoli",
          grams: 120,
          calories: 42,
          protein: 3.5,
          carbs: 8,
          fats: 0.5,
          image: null,
          type: "food",
          per100: { calories: 35, protein: 2.8, carbs: 7, fats: 0.4 },
        },
      ],
      ml_tag: "Safety",
    },
    {
      id: "safety-lunch-2",
      title: "Turkey Wrap + Apple + Water",
      explanation: "Safety fallback: moderate-calorie lunch for day-to-day consistency.",
      items: [
        {
          id: "safety-wrap",
          title: "Turkey Wrap",
          grams: 240,
          calories: 360,
          protein: 28,
          carbs: 36,
          fats: 12,
          image: null,
          type: "food",
          per100: { calories: 150, protein: 11.7, carbs: 15, fats: 5 },
        },
        {
          id: "safety-apple",
          title: "Apple",
          grams: 130,
          calories: 68,
          protein: 0.4,
          carbs: 18,
          fats: 0.2,
          image: null,
          type: "food",
          per100: { calories: 52, protein: 0.3, carbs: 14, fats: 0.2 },
        },
        {
          id: "safety-water",
          title: "Water",
          grams: 250,
          calories: 0,
          protein: 0,
          carbs: 0,
          fats: 0,
          image: null,
          type: "food",
          per100: { calories: 0, protein: 0, carbs: 0, fats: 0 },
        },
      ],
      ml_tag: "Safety",
    },
  ],
  dinner: [
    {
      id: "safety-dinner-1",
      title: "Salmon + Sweet Potato + Salad",
      explanation: "Safety fallback: balanced dinner with healthy fats and fiber.",
      items: [
        {
          id: "safety-salmon",
          title: "Grilled Salmon",
          grams: 170,
          calories: 353,
          protein: 34,
          carbs: 0,
          fats: 22,
          image: null,
          type: "food",
          per100: { calories: 208, protein: 20, carbs: 0, fats: 13 },
        },
        {
          id: "safety-sweetpotato",
          title: "Sweet Potato",
          grams: 170,
          calories: 146,
          protein: 2.7,
          carbs: 34,
          fats: 0.2,
          image: null,
          type: "food",
          per100: { calories: 86, protein: 1.6, carbs: 20, fats: 0.1 },
        },
        {
          id: "safety-salad",
          title: "Mixed Salad",
          grams: 120,
          calories: 24,
          protein: 2,
          carbs: 4,
          fats: 0.2,
          image: null,
          type: "food",
          per100: { calories: 20, protein: 1.7, carbs: 3.7, fats: 0.2 },
        },
      ],
      ml_tag: "Safety",
    },
    {
      id: "safety-dinner-2",
      title: "Tofu Stir Fry + Brown Rice + Green Tea",
      explanation: "Safety fallback: plant-forward dinner for steady macro balance.",
      items: [
        {
          id: "safety-tofu",
          title: "Tofu Stir Fry",
          grams: 220,
          calories: 316,
          protein: 20,
          carbs: 22,
          fats: 14,
          image: null,
          type: "food",
          per100: { calories: 144, protein: 9, carbs: 10, fats: 8 },
        },
        {
          id: "safety-rice2",
          title: "Brown Rice",
          grams: 120,
          calories: 133,
          protein: 3,
          carbs: 28,
          fats: 1,
          image: null,
          type: "food",
          per100: { calories: 111, protein: 2.6, carbs: 23, fats: 0.9 },
        },
        {
          id: "safety-tea",
          title: "Green Tea",
          grams: 250,
          calories: 2,
          protein: 0,
          carbs: 0,
          fats: 0,
          image: null,
          type: "food",
          per100: { calories: 0.8, protein: 0, carbs: 0, fats: 0 },
        },
      ],
      ml_tag: "Safety",
    },
  ],
};
