CREATE TABLE "nutrition_profiles" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "nutrition_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"basis_quantity" numeric(12, 4) NOT NULL,
	"basis_unit" text NOT NULL,
	"basis_state" text NOT NULL,
	"calories_kcal" numeric(12, 4),
	"energy_kj" numeric(12, 4),
	"protein_g" numeric(12, 4),
	"carbohydrate_g" numeric(12, 4),
	"carbohydrate_basis" text NOT NULL,
	"fat_g" numeric(12, 4),
	"saturated_fat_g" numeric(12, 4),
	"trans_fat_g" numeric(12, 4),
	"polyunsaturated_fat_g" numeric(12, 4),
	"monounsaturated_fat_g" numeric(12, 4),
	"cholesterol_mg" numeric(12, 4),
	"sodium_mg" numeric(12, 4),
	"potassium_mg" numeric(12, 4),
	"fiber_g" numeric(12, 4),
	"sugar_g" numeric(12, 4),
	"added_sugars_g" numeric(12, 4),
	"vitamin_d_mcg" numeric(12, 4),
	"calcium_mg" numeric(12, 4),
	"iron_mg" numeric(12, 4),
	"vitamin_a_mcg" numeric(12, 4),
	"vitamin_a_convention" text,
	"vitamin_c_mg" numeric(12, 4),
	"calculation_method" text NOT NULL,
	"confidence" numeric(5, 4),
	"source_name" text NOT NULL,
	"source_license" text NOT NULL,
	"source_derivation" text,
	"calculated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "nutrition_profiles_basis_state_check" CHECK ("nutrition_profiles"."basis_state" IN ('as_sold','edible_portion','prepared')),
	CONSTRAINT "nutrition_profiles_carbohydrate_basis_check" CHECK ("nutrition_profiles"."carbohydrate_basis" IN ('by_difference','available')),
	CONSTRAINT "nutrition_profiles_vitamin_a_convention_check" CHECK ("nutrition_profiles"."vitamin_a_convention" IS NULL OR "nutrition_profiles"."vitamin_a_convention" IN ('rae','re')),
	CONSTRAINT "nutrition_profiles_calculation_method_check" CHECK ("nutrition_profiles"."calculation_method" IN ('lab','label','ingredient_calculation','manual','scaled_from_per_100g')),
	CONSTRAINT "nutrition_profiles_source_derivation_check" CHECK ("nutrition_profiles"."source_derivation" IS NULL OR "nutrition_profiles"."source_derivation" IN
        ('analysed','label_data','recipe','borrowed','imputed','estimated','unknown')),
	CONSTRAINT "nutrition_profiles_confidence_check" CHECK ("nutrition_profiles"."confidence" IS NULL OR ("nutrition_profiles"."confidence" >= 0 AND "nutrition_profiles"."confidence" <= 1)),
	CONSTRAINT "nutrition_profiles_nutrients_non_negative" CHECK (LEAST(
      "nutrition_profiles"."calories_kcal", "nutrition_profiles"."energy_kj", "nutrition_profiles"."protein_g", "nutrition_profiles"."carbohydrate_g",
      "nutrition_profiles"."fat_g", "nutrition_profiles"."saturated_fat_g", "nutrition_profiles"."trans_fat_g", "nutrition_profiles"."polyunsaturated_fat_g",
      "nutrition_profiles"."monounsaturated_fat_g", "nutrition_profiles"."cholesterol_mg", "nutrition_profiles"."sodium_mg", "nutrition_profiles"."potassium_mg",
      "nutrition_profiles"."fiber_g", "nutrition_profiles"."sugar_g", "nutrition_profiles"."added_sugars_g", "nutrition_profiles"."vitamin_d_mcg",
      "nutrition_profiles"."calcium_mg", "nutrition_profiles"."iron_mg", "nutrition_profiles"."vitamin_a_mcg", "nutrition_profiles"."vitamin_c_mg",
      "nutrition_profiles"."basis_quantity"
    ) >= 0)
);
